### ISSUE TITLE
Code is expecting all operations to have response from DB

### ISSUE THREAD

**Issue by ardalanrazavi** [reflection/sqlalchemy-clickhouse#2]
Not all operations have response (Update, Write, and some other operations don't return anything in many cases).
Below is the example of executing 'FREEZE' operation which cause exception to be thrown:

>>> from sqlalchemy import create_engine
>>> engine = create_engine('clickhouse://default:@ch/default')
>>> ch_client = engine.connect()ch_client.execute("alter table dummy_table freeze partition 20190115")

`
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 942, in execute
    return self._execute_text(object, multiparams, params)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1104, in _execute_text
    statement, parameters
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
    context)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1416, in _handle_dbapi_exception
    util.reraise(*exc_info)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 249, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 509, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy_clickhouse/connector.py", line 243, in execute
    self._process_response(response)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy_clickhouse/connector.py", line 373, in _process_response
    model = next(response)
RuntimeError: generator raised StopIteration
generator raised StopIteration
`

**Comment by reflection** [comment]
One workaround for now would be to get the raw dbapi object and call execute() directly with is_response set to False.  Example:

```
from sqlalchemy import create_engine

engine = create_engine('clickhouse://default:@ch-0/default')
conn = engine.raw_connection()
cur = conn.cursor()
cur.execute('ALTER TABLE dummy_table FREEZE PARTITION 20190115', is_response=False)
```

By the way, I just implemented support for the ClickHouse http _session_id_ param to be set in the connection string itself and sent with subsequent queries (be mindful of the default 60s timeout for http sessions).  Example:
```
from sqlalchemy import create_engine

engine = create_engine('clickhouse://default:@ch-0/default?session_id=test')
conn = engine.raw_connection()
cur = conn.cursor()
cur.execute('SET max_threads=1', is_response=False)
```
